#!/usr/bin/env bash
# Bash script that displays a list of currently running processes
#   shows all processes for all users, including those who might not have a TTY
#   Display in a user-oriented format
#   show process hierarchy

ps -auxf
