#!/usr/bin/env bash
# Bash script that displays the contents of the file '/etc/passwd'
# Onlu displays: username, user id and Home directory path foe the user.

while read -r passwd; do
    echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
