#!/usr/bin/env bash
# bash script that displays 'Best School' 10 times in stdout
# displays 'Best School' then 'Hi' on a new line on the 9th iteration

count=0

while [ $count -lt 10 ]
do
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    (( count++ ))
done
