#!/usr/bin/env bash
# bash script that loops from 1 to 20
# displays iteration number for all iteration.
# displays "bad luck from China" on the first iteration
# "bad luck from Japan" on the second iteration
# "bad luck from Italy" on the second iteration

count=1

while [ $count -le 20 ]
do
    echo "$count"
    case $count in
        "4") echo "bad luck from China";;
        "9") echo "bad luck from Japan";;
        "17") echo "bad luck from Italy";;
    esac
    (( count++ ))
done
