#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# displays hours from 0 to 12
# displays minutes from 1 to 59

hour_count=0

while [ $hour_count -le 12 ]
do
    echo "Hour: $hour_count"
    minute=1
    while [ $minute -le 59 ]
    do
        echo "$minute"
        (( minute++ ))
    done
    (( hour_count++ ))
done
