#!/usr/bin/env bash
# This bash script diaplays the content of the current in a list format
# Where only the part of the name after the first dash is displayed

list=$(ls)
for i in $list; do
    echo "$i" | cut -d '-' -f2
done
