#!/usr/bin/env bash
# Bash script that gives information about 'school' file
# prints "school file exists" if the file exists
# prints "school file is empty" if it is empty
# prints "school file is not empty" if school file is not empty
# prints "school is a regular file" if it is a regular file
# prints "school file does not exist" if the file does not exist

if [-e "school" ]
then
    echo "school fie exists"
    if [ -s "school" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f "school" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
